### ISSUE TITLE
[Feature Request] New downloads open 'chrome://downloads' in a new tab?

### ISSUE THREAD

**Issue by austin-guevara** [ivan7237d/disable-downloads-bar#2]
New downloads would open `chrome://downloads` instead of the classic downloads bar. Is that within the scope of this project?

Thanks!

**Comment by ivan7237d** [comment]
I like how this extension is small and it's easy to communicate what it does, so I think that's outside the scope, but thanks for the suggestion.

**Comment by austin-guevara** [comment]
I went ahead and created the functionality myself – [Chrome Downloads Tabber](https://github.com/austin-guevara/chrome-downloads-tabber). Cheers!

**Comment by ivan7237d** [comment]
@austin-guevara Yes, it's more than sufficient, thanks vm for the mention!

**Comment by T-Cubed** [comment]
Hey Ivan, I have Chromium Version 64.0.3282.119 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (32-bit) and disable-downloads works with the regular window, but not incognito ones (even though I've checked the "Allow in incognito" box.  Have you heard of this happening before? Is there any other information I can send you on this to help fix it?

**Comment by ivan7237d** [comment]
@T-Cubed Thanks for feedback. No, didn't realize that it wasn't working in Incognito mode even if you enabled it. This is related to https://bugs.chromium.org/p/chromium/issues/detail?id=258036. I think one could implement a workaround of some kind, like calling `disableShelf` whenever a new window opens, but unfortunately I don't have time to do that right now. If you have more comments, pls file a new issue because this thread is about another issue.
